python FeatureSelectionUsingIG.py
python main.py
python nn_spam_ham_cross_entropy_batch_gradient_descent.py > console_outputs/nn_spam_ham_cross_entropy_batch_gradient_descent.txt
python nn_spam_ham_cross_entropy_minibatch_gradient_descent.py > console_outputs/nn_spam_ham_cross_entropy_minibatch_gradient_descent.txt
python nn_spam_ham_cross_entropy_stochastic_gradient_descent.py > console_outputs/nn_spam_ham_cross_entropy_stochastic_gradient_descent.txt
python nn_spam_ham_mse_batch_gradient_descent.py > console_outputs/nn_spam_ham_mse_batch_gradient_descent.txt
python nn_spam_ham_mse_minibatch_gradient_descent.py > console_outputs/nn_spam_ham_mse_minibatch_gradient_descent.txt
python nn_spam_ham_mse_stochastic_gradient_descent.py > console_outputs/nn_spam_ham_mse_stochastic_gradient_descent.txt
pause
